# Листинг 10.4 Искусственное генерирование исключений

print("Начинаем генерировать ошибки")
# Создание объекта исключения
error = Exception("Первая ошибка")
# Первый блок контролируемого кода
try:
    # Второй блок контролируемого кода
    try:
        # Третий блок контролируемого кода 
        try:
            # Генерирование исключения
            raise error
        # Обаботка исключения для третьего блока
        except:
            print(error)
            # Повторное генерирование исключения
            raise
        # Обработка исключения для второго блока
    except Exception as e:
        print("Повторная обработка:")
        print(e)
        # Внутрений блок контролируемого кода
        try:
            # Генерирование исключения
            raise ArithmeticError("Вторая ошибка")
        # Обработка исключения для внутреннего блока
        except ArithmeticError as e:
            print(e)
        # Генерирование исключения
        raise Warning
# Обработка исключения для первого блока
except Warning:
    print("Еще одна ошибка")
print("Ошибок больше нет")